name: Azure VM Automation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup PowerShell
         uses: PowerShell/PowerShell@v1


      - name: Run VM Script
        run: |
          pwsh ./create-vm.ps1
