
name: Azure VM Automation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Az module
      shell: pwsh
      run: |
        Install-Module -Name Az -Scope CurrentUser -Force -AllowClobber
        Import-Module Az

    - name: Run PowerShell script
      shell: pwsh
      run: |
        ./create-vm.ps1
