name: PowerShell Azure VM Creation

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PowerShell
        uses: PowerShell/setup-powershell@v1

      - name: Install Az Module
        run: |
          Install-Module -Name Az -Force -Scope CurrentUser -AllowClobber
        shell: pwsh

      - name: Run script
        run: |
          pwsh ./create-vm.ps1
