name: Azure VM Creation with PowerShell

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install PowerShell Az module
        run: |
          pwsh -Command "Install-Module -Name Az -Force -Scope CurrentUser -AllowClobber"
      
      - name: Run VM creation script
        run: |
          pwsh ./create-vm.ps1
