name: Azure PowerShell VM Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install Az Module
      shell: pwsh
      run: |
        Install-Module -Name Az -Scope CurrentUser -Force -AllowClobber
        Import-Module Az
        Get-Module Az -ListAvailable

    - name: Run PowerShell Script
      shell: pwsh
      run: |
        ./create-vm.ps1
