
name: Azure VM Automation

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup PowerShell Core
      uses: PowerShell/PowerShell@v1

    - name: Install Az Module
      shell: pwsh
      run: |
        Install-Module -Name Az -Scope CurrentUser -Force -AllowClobber
        Import-Module Az

    - name: Run PowerShell Script
      shell: pwsh
      run: |
        ./create-vm.ps1


   
